// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/kava-labs/kava/x/liquidator/types
// ALIASGEN: github.com/kava-labs/kava/x/liquidator/keeper
package liquidator

import (
	"github.com/kava-labs/kava/x/liquidator/keeper"
	"github.com/kava-labs/kava/x/liquidator/types"
)

const (
	ModuleName              = types.ModuleName
	StoreKey                = types.StoreKey
	RouterKey               = types.RouterKey
	QuerierRoute            = types.QuerierRoute
	DefaultParamspace       = types.DefaultParamspace
	DefaultCodespace        = types.DefaultCodespace
	QueryGetOutstandingDebt = types.QueryGetOutstandingDebt
)

var (
	// functions aliases
	RegisterCodec             = types.RegisterCodec
	SumDeposits               = types.SumDeposits
	SumPartialDeposits        = types.SumPartialDeposits
	SumCoins                  = types.SumCoins
	SumDebt                   = types.SumDebt
	CalculateRatableDebtShare = types.CalculateRatableDebtShare
	DefaultGenesisState       = types.DefaultGenesisState
	ValidateGenesis           = types.ValidateGenesis
	GetAuctionIDBytes         = types.GetAuctionIDBytes
	GetAuctionIDFromBytes     = types.GetAuctionIDFromBytes
	NewParams                 = types.NewParams
	ParamKeyTable             = types.ParamKeyTable
	DefaultParams             = types.DefaultParams
	CalculateSharesPercentage = types.CalculateSharesPercentage
	NewKeeper                 = keeper.NewKeeper
	NewQuerier                = keeper.NewQuerier

	// variable aliases
	ModuleCdc                  = types.ModuleCdc
	CollateralAuctionKeyPrefix = types.CollateralAuctionKeyPrefix
	TotalCollateralPrefix      = types.TotalCollateralPrefix
	KeyDebtAuctionSize         = types.KeyDebtAuctionSize
	KeyCollateralParams        = types.KeyCollateralParams
)

type (
	PartialDeposit     = types.PartialDeposit
	PartialDeposits    = types.PartialDeposits
	GenesisState       = types.GenesisState
	CollateralDeposit  = types.CollateralDeposit
	CollateralDeposits = types.CollateralDeposits
	Params             = types.Params
	CollateralParam    = types.CollateralParam
	CollateralParams   = types.CollateralParams
	Keeper             = keeper.Keeper
)
